### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Bolshaksa** [Sadzurami/Quick-IPv6Proxy-Installer#2]
How to change any settings? (For example password for proxy access)

**Comment by Sadzurami** [comment]
You define all access settings when you run the script.

Or in the file ~/3proxy/3proxy.cfg

**Comment by Bolshaksa** [comment]
Thanks for the answer!
It's just that by default the password is generated with special characters, for example @, which is not correctly accepted everywhere. Therefore, there was a need to change the password.

Does the script only work in rotation mode? Is it possible to somehow create / get a list of ipv6 addresses to save the session with the current IP address for specific tasks.
